"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[I>](green)"
error_symbol = "[I>](green)"
vicmd_symbol = "[N>](red)"
vimcmd_replace_one_symbol = "[r>](purple)"
vimcmd_replace_symbol = "[R>](purple)"
vimcmd_visual_symbol = "[V>](purple)"

[status]
disabled = false
